[ADD] 회원 로그인 API
wecode-bootcamp-korea/37-1st-ZINWOOS-backend pull request #7
Opened 2022-09-22 04:33 UTC by walter811

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원 로그인 기능 구현
- req.body로 받아온 이메일로 해당 유저 정보가 DB에 있는지 검색하는 기능 추가
- req.body로 받아온 비밀번호를 bcrypt.compare 를 사용해 비교하는 기능 추가

2. jsonwebtoken 발급 및 검증 기능 구현
- 로그인 과정에서 예외 사항이 없을 시 jsonwebtoken을 발급하는 기능 추가
- 발급한 jsonwebtoken을 검증할 수 있는 auth.js 파일 추가
 

4. error handler 기능 구현
- 비동기 에러를 처리해주는 asyncWrap 기능 추가
- 에러 핸들링 미들웨어인 globalErrorHandler 기능 추가

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다.
- 에러 핸들링, 인증 및 인가 관련 코드들을 더 잘 사용할 수 있게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-09-22 04:39 UTC, walter811 commented
[
<img width="331" alt="스크린샷 2022-09-22 오후 1 10 26" src="https://user-images.githubusercontent.com/104759273/191659632-f6e92a76-d593-4500-97fb-bbe42c29b343.png">
](url)
[
<img width="1316" alt="스크린샷 2022-09-22 오후 1 09 58" src="https://user-images.githubusercontent.com/104759273/191659663-a1e21210-0456-4f15-836c-6fc9ca327334.png">
](url)
[
<img width="1316" alt="스크린샷 2022-09-22 오후 1 09 58" src="https://user-images.githubusercontent.com/104759273/191659682-c5547ab4-dcc8-4855-bb03-4aab1bad16bb.png">
](url)

잘 구현됩니다 :)

2022-09-22 09:05 UTC, Kang-kyunghun requested changes

2022-09-22 09:05 UTC, Kang-kyunghun commented on api/services/userService.js
> +    validator.validatePassword(password);
로그인 할 때는 해당 validator가 필요하지 않을 것 같습니다.
이미 회원 가입 할 때 전부 처리 한 것이기 때문에, DB에 저장된 값으로만 비교해 주세요.

2022-09-22 09:05 UTC, Kang-kyunghun commented on api/services/userService.js
> +        const error = new Error('User not found');
로그인 에러 처리 시에는 ID가 틀렸는지 Password가 틀렸는지 모르게 하는 것이 좋습니다.

```suggestion
        const error = new Error('Invalid user');
```

2022-09-22 09:05 UTC, Kang-kyunghun commented on api/services/userService.js
> +        error.statusCode = 404;
```suggestion
        error.statusCode = 401;
```

2022-09-22 09:05 UTC, Kang-kyunghun commented on api/services/userService.js
> +        throw error;
```suggestion
    if (!match) {
        const error = new Error('Invalid user');
        error.statusCode = 401;
        throw error;
```

2022-09-22 09:05 UTC, Kang-kyunghun commented on api/utils/auth.js
> +        throw error;
사용자에 대한 데이터가 없기 때문에 404 not found를 사용한 것으로 보입니다. 만약 제품이나 장바구니 같은 데이터 였다면 괜찮았을 것 같은데, 사용자 데이터는 결국 권한과 연관 있는 데이터로 볼 수 있습니다.
따라서 권한과 관련된 status code로 401을 사용하시면 좋을 것 같습니다.
 
```suggestion
        const error = new Error('Invalid user');
        error.statucCode = 401;
        throw error;
```

2022-09-23 02:03 UTC, walter811 commented
수정사항 반영 완료했습니다 :)

2022-09-23 02:49 UTC, Kang-kyunghun commented
LGTM

2022-09-23 02:49 UTC, merged