상품 세부정보 페이지 api
wecode-bootcamp-korea/37-1st-ZINWOOS-backend pull request #8
Opened 2022-09-26 06:36 UTC by ChoiRamsey

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [v ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 세부정보 페이지(상품리스트에서 특정 상품 클릭시 이동)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 세부 정보 구현
- 상품명, 요약설명, 가격, 세부설명, 세부이미지, 상품이미지, 옵션명, 옵션가격, 메인카테고리, 서브카테고리 전송

2. 로그인 데이터 처리

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 하나의 상품별로 다양한 이미지가 필요한 상황에서 쿼리문 작성 시 배열로 담아 주는 방법을 연습할 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-09-27 02:57 UTC, Kang-kyunghun requested changes

2022-09-27 02:57 UTC, Kang-kyunghun commented on api/controllers/itemController.js
> +}
- if같이 새로운 구문이 시작 되면 공백을 주어서 가독성을 높여주면 좋을 것 같습니다.
- itemService.getItemById을 통해서 가지고 온 결과물이 결국 item이므로 변수면을 item으로 바꾸면 더 좋을 것 같아요.
- 상태코드 201은 created를 의미합니다. 200으로 수정해 주세요/

```suggestion
    const itemId = req.params.itemId;
    
    if (!itemId) {
      return res.status(400).json({ message : 'KEY_ERROR' });
    }
   
     const item = await itemService.getItemById(itemId);
    return res.status(200).json({ data : item });
  } catch (err) {
    console.log(err);
    return res.status(err.statusCode || 500).json({ message : err.message });
  }
}
```

2022-09-27 02:57 UTC, Kang-kyunghun commented on api/services/userService.js
> +    validator.validatePassword(password);
로그인 같은 경우 굳이 validator가 필요하지 않습니다.
로그인 자체게 DB에 있는 데이터와 비교하는 것이기 때문입니다.

2022-09-27 02:57 UTC, Kang-kyunghun commented on api/models/itemDao.js
> +const readItems = async () => {
```suggestion
const readAllItems = async () => {
```

2022-09-27 02:57 UTC, Kang-kyunghun commented on api/models/itemDao.js
> +  const itemImages = await dataSource.query(
item에 있는 이미지들을 가져오고 싶어하는 것으로 보입니다. 그럴 때는 2번의 query가 아닌 한 번에 불러올 수 있는 방법이 있습니다.

아래 링크를 참고해서 한 번 수정해 보세요.
http://52.78.22.201/tutorials/weplanet/mysql-json-object/

2022-09-27 02:57 UTC, Kang-kyunghun commented on api/services/itemService.js
> +  return oneItem;
```suggestion
  const Item = await itemDao.readItem(itemId);
  return Item;
```

2022-09-27 11:36 UTC, ChoiRamsey commented
수정사항 전부 반영했습니다.

2022-09-28 01:05 UTC, Kang-kyunghun commented
1. 불필요한 주석 삭제
2. PR에 올라오면 안 되는 파일들 제거

2022-09-28 01:54 UTC, ChoiRamsey commented
주석 삭제 및 파일 제거 반영했습니다.

2022-09-28 02:41 UTC, ChoiRamsey commented
itemDao 에 쿼리문 수정하여 최종 수정했습니다.

2022-09-28 08:47 UTC, Kang-kyunghun commented
LGTM

2022-09-28 08:47 UTC, merged