[ADD] 장바구니 기능 구현
wecode-bootcamp-korea/37-1st-ZINWOOS-backend pull request #9
Opened 2022-09-26 06:57 UTC by walter811

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 CRUD 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 장바구니 상품 추가 기능
- 중복 상품 추가 시 갯수만 추가
2. 장바구니 리스트 불러오기 기능
3. 장바구니 상품 삭제 기능
- 쿼리스트링을 통해 선택한 항목 전부 삭제

(장바구니 상품 주문 기능은 추후 추가 예정)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- CRUD 기능을 전부 적용하면서 코드 작성에 익숙해질 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 상품 목록 수정, 삭제 시 transaction을 반드시 적용해야 할까요? 적용해야 한다면 참고할만한 공식문서가 있는지 궁금합니다.

2022-09-26 06:59 UTC, walter811 commented
경훈님 장바구니 기능 API 전달드립니다!
한번에 보내서 죄송합니다 확인 및 리뷰 부탁드립니다 감사합니다 :)

2022-09-27 03:13 UTC, Kang-kyunghun requested changes

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +    const { itemId } = req.params;
add cart이면 post method이고 따라서  body가 존재하는 params로 받는 이유가 있나요?
그리고 params로 받는다고 해도 restful하지 않기 때문에 body로 받는 것이 좋을 것 같아요.

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +    res.status(201).json({ message:'Item deleted successfully'})
적절한 상태코드를 사용해 주세요.

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +        await cartService.resetCartList();
빈 배열일 때 조건 같은데, 해당 조건이 필유한 이유를 코멘트로 남겨주세요.

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +}
해당 코드는 불필요해 보이는데, 왜 AUTO_INCREMENT = 1로 다시 지정하시나요?

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/routes/cartRouter.js
> +cartRouter.delete('/delete', loginRequired, cartController.deleteCart);
- restful에 맞게 URI에는 동사를 사용하지 않고, HTTP method로 행위를 나타냅니다.
```suggestion
cartRouter.delete('/, loginRequired, cartController.deleteCart);
```

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +const checkOverlap = async (userId, itemId, optionId) => {
cart 존재 여부 확인을 위한 것이라면 select *로 전부 데이터를 가지고 오지말고 EXIST를 구문을 활용해 보세요.

2022-09-27 03:13 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +const addQuantity = async (userId, itemId, quantity, optionId) => {
단수 수량 추가의 의미보다는 cart를 업데이트 한다는 의미가 더 좋을 것 같습니다.
```suggestion
const updateCart = async (userId, itemId, quantity, optionId) => {
```

2022-09-27 03:26 UTC, walter811 commented on api/controllers/cartController.js
> +        await cartService.resetCartList();
아 해당 코드는 저 혼자 테스트할때 cart id 값이 계속 늘어나는게 보기가 불편해서 넣어둔거라 삭제하도록 하겠습니다 :)

2022-09-27 03:31 UTC, walter811 commented on api/models/cartDao.js
> +}
위에 남긴 코멘트와 같은 이유입니다 삭제하도록 하겠습니다 :)

2022-09-27 04:30 UTC, walter811 commented
리뷰 사항 반영했습니다 감사합니다 :)

2022-09-27 05:49 UTC, walter811 commented
쿼리 조건문쪽 문제로 자꾸 에러가 떠서 option_id 값이 있는 경우와 null 인경우의 코드를 나눠서 수정했습니다. 혹시 이렇게 나누는 법 말고 한번에 쿼리문을 작성하는 방법이 있을까요?

2022-09-27 08:13 UTC, Kang-kyunghun requested changes

2022-09-27 08:13 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +    res.status(201).json({ cartList })
상태코드 확인하고 수정해 주세요.

2022-09-27 08:13 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +}
해당 쿼리가 User Dao에는 없나요???

2022-09-27 08:13 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +
- 존재 여부만 확인 하는 코드면 다음과 같이 수정하면 좋을 것 같아요
```suggestion
        `SELET EXISTS  (
            SELECT 
              id 
            FROM carts
            WHERE user_id = ?
            AND item_id = ?
            AND option_id = ?
          ) AS is_existed
        )
        `, [userId, itemId, optionId]
    )

```

2022-09-27 08:14 UTC, Kang-kyunghun commented
SQL에서도 IF를 사용할 수 있습니다.
IF를 사용해서 Dao를 하나로 합쳐보고, 그에 맞게 service도 수정해 주세요.

2022-09-27 12:22 UTC, walter811 commented
성공한 것 같습니다.. 수정 사항 일단 push 드립니다. 
내일 오전에 오셔서 한번 봐주시면 감사하겠습니다 ㅠ

2022-09-28 01:14 UTC, Kang-kyunghun requested changes

2022-09-28 01:14 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +    const { optionId } = req.body;
delete method에는 body가 존재하지 않습니다. 따라서 데이터를 받으려면 query parameter를 이용해야 합니다.

2022-09-28 01:14 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +    console.log(optionId)
콘솔은 지워주세요.

2022-09-28 01:14 UTC, Kang-kyunghun commented on api/controllers/cartController.js
> +        await cartService.deleteCart(+userId, +itemId[i], optionId[i])
for문을 돌리지 말고 배열 그대로 Dao까지 넘겨서 IN을 사용하는 것은 어떨까요?
sql에서 IN을 사용하면 한 조건에 대해 한 번에 여러 값을 받을 수 있습니다.

2022-09-28 01:14 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +        ) AS is_existed
select에서 사용한 IF가 아니므로 뒤에 AS가 없어도 될 것 같은데 한 번 확인해 주세요.
```suggestion
        ) 
```

2022-09-28 01:14 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +        AND (
컨트롤러에서 말한 IN을 사용하면 좋을 것 같은 부분 입니다.
```suggestion
        AND item_id IN ?
        AND (
```

2022-09-28 01:14 UTC, Kang-kyunghun commented on api/models/cartDao.js
> +
불필요한 공백은 제거해 주세요.

2022-09-28 01:15 UTC, Kang-kyunghun commented
1. 수정사항 반영해 주세요.
2. .DS_Store 파일은 PR에 올라오면 안 됩니다. 제거하고 gitignore에 추가해 주세요.

2022-09-28 01:28 UTC, walter811 commented on api/models/cartDao.js
> +        ) AS is_existed
삭제하니 리턴되는 결과에 쿼리문이 찍혀서 일단은 두도록 하겠습니다!

2022-09-28 04:42 UTC, walter811 commented
수정사항 반영해서 push 했습니다 확인 부탁드립니다 :)

2022-09-28 08:27 UTC, Kang-kyunghun requested changes

2022-09-28 08:27 UTC, Kang-kyunghun commented on app.js
> +app.use(express.urlencoded({ extended: false }));
해당 미들웨어를 사용한 이유가 있을까요??

2022-09-28 08:27 UTC, Kang-kyunghun commented on api/routes/cartRouter.js
> +cartRouter.delete('/', loginRequired, cartController.deleteCart);
```suggestion
cartRouter.get('', loginRequired, cartController.getCartList);
cartRouter.post('', loginRequired, cartController.addCart);
cartRouter.delete('', loginRequired, cartController.deleteCart);
```

2022-09-28 09:06 UTC, walter811 commented on app.js
> +app.use(express.urlencoded({ extended: false }));
아 저번에 제오류인줄 알고 바디파서 이것저것 찾아서 사용해봤는데 사실 제 문제가 아니었습니다 삭제하겠습니다 :)

2022-09-28 09:08 UTC, walter811 commented
수정 완료했습니다 :)

2022-09-29 02:00 UTC, merged